# Generated by Django 5.0.1 on 2024-02-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Mahsulot Rasmi', 'verbose_name_plural': 'Mahsulot Rasmlari'},
        ),
    ]
