# Generated by Django 5.0.1 on 2024-02-13 14:14

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1098, 717], upload_to='images/products'),
        ),
    ]
