# Generated by Django 5.0.2 on 2024-02-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_change', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Sahifa sozlamasi',
                'verbose_name_plural': 'Sahifa sozlamalari',
            },
        ),
    ]
